/*
 * @Description:
 * @Date: 2024-04-10 17:30:49
 * @LastEditTime: 2024-10-10 21:09:36
 */
import ProButton from "@element-plus-ui/pro-button";
import ProDescriptions from "@element-plus-ui/pro-descriptions";
import {
  ProField,
  ProFieldUploadAvatar,
  ProFieldCascader,
  ProFieldCheckbox,
  ProFieldCheckboxButton,
  ProFieldColor,
  ProFieldDate,
  ProFieldDateMonth,
  ProFieldDateMonthRange,
  ProFieldDateRange,
  ProFieldDates,
  ProFieldDateTime,
  ProFieldDateTimeRange,
  ProFieldDateWeek,
  ProFieldDateYear,
  ProFieldUploadImage,
  ProFieldNumber,
  ProFieldPassword,
  ProFieldRadio,
  ProFieldRadioButton,
  ProFieldRate,
  ProFieldSelect,
  ProFieldSlider,
  ProFieldSwitch,
  ProFieldText,
  ProFieldTextarea,
  ProFieldTime,
  ProFieldTimeRange,
  ProFieldTimeSelect,
  ProFieldTreeSelect
} from "@element-plus-ui/pro-field";
import {
  ProForm,
  ProFormUploadAvatar,
  ProFormCascader,
  ProFormCheckbox,
  ProFormCheckboxButton,
  ProFormColor,
  ProFormDate,
  ProFormDateMonth,
  ProFormDateMonthRange,
  ProFormDateRange,
  ProFormDates,
  ProFormDateTime,
  ProFormDateTimeRange,
  ProFormDateWeek,
  ProFormDateYear,
  ProFormUploadImage,
  ProFormNumber,
  ProFormPassword,
  ProFormRadio,
  ProFormRadioButton,
  ProFormRate,
  ProFormSelect,
  ProFormSlider,
  ProFormSwitch,
  ProFormText,
  ProFormTextarea,
  ProFormTime,
  ProFormTimeRange,
  ProFormTimeSelect,
  ProFormTreeSelect,
  ProFormVirtualizedSelect
} from "@element-plus-ui/pro-form";
import ProTable from "@element-plus-ui/pro-table";
import ProText from "@element-plus-ui/pro-text";
// import ProTabs from "@element-plus-ui/pro-tabs";
import markInstaller from "./mark-installer";

export default markInstaller({
  ProTable,
  ProText,
  ProButton,
  ProDescriptions,
  ProField,
  ProFieldUploadAvatar,
  ProFieldCascader,
  ProFieldCheckbox,
  ProFieldCheckboxButton,
  ProFieldColor,
  ProFieldDate,
  ProFieldDateMonth,
  ProFieldDateMonthRange,
  ProFieldDateRange,
  ProFieldDates,
  ProFieldDateTime,
  ProFieldDateTimeRange,
  ProFieldDateWeek,
  ProFieldDateYear,
  ProFieldUploadImage,
  ProFieldNumber,
  ProFieldPassword,
  ProFieldRadio,
  ProFieldRadioButton,
  ProFieldRate,
  ProFieldSelect,
  ProFieldSlider,
  ProFieldSwitch,
  ProFieldText,
  ProFieldTextarea,
  ProFieldTime,
  ProFieldTimeRange,
  ProFieldTimeSelect,
  ProFieldTreeSelect,
  ProForm,
  ProFormRate,
  ProFormUploadImage,
  ProFormColor,
  ProFormUploadAvatar,
  ProFormSlider,
  ProFormSwitch,
  ProFormSelect,
  ProFormTreeSelect,
  ProFormText,
  ProFormNumber,
  ProFormPassword,
  ProFormTextarea,
  ProFormCascader,
  ProFormRadio,
  ProFormRadioButton,
  ProFormCheckbox,
  ProFormCheckboxButton,
  ProFormTime,
  ProFormTimeRange,
  ProFormTimeSelect,
  ProFormDate,
  ProFormDates,
  ProFormDateRange,
  ProFormDateTime,
  ProFormDateTimeRange,
  ProFormDateWeek,
  ProFormDateMonth,
  ProFormDateMonthRange,
  ProFormDateYear,
  ProFormVirtualizedSelect
});
